@startuml

!theme hacker
top to bottom direction
skinparam linetype ortho

rectangle IShape
rectangle Shape
rectangle Circle
rectangle Hexagon
rectangle Rectangle
rectangle Triangle

Circle     -[#039ba1,dashed]-^  IShape    
Hexagon    -[#039ba1,dashed]-^  IShape    
Rectangle  -[#039ba1,dashed]-^  IShape    
Triangle   -[#039ba1,dashed]-^  IShape    

@enduml